name: Windows Build and Release

on:
  push:
    tags:
      - 'v*'    # 当推送标签（如 v1.0.0）时自动触发
  workflow_dispatch:    # 支持手动触发

jobs:
  build-and-release:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --distpath dist/ main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: CloudreveDownloader
        path: dist/main.exe

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name || 'manual-trigger' }}
        release_name: Release ${{ github.ref_name || 'Manual Trigger' }}
        draft: false
        prerelease: false

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/main.exe
        asset_name: CloudreveDownloader.exe
        asset_content_type: application/octet-stream
